ignoredBuiltDependencies:
  - sharp
  - unrs-resolver
onlyBuiltDependencies:
  - '"'
  - ','
  - '-'
  - '3'
  - '@prisma/client'
  - '@prisma/engines'
  - '['
  - ']'
  - a
  - b
  - d
  - e
  - esbuild
  - h
  - i
  - l
  - p
  - prisma
  - q
  - r
  - s
  - t
  - u
